# Generated by Django 3.2.5 on 2021-09-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='_location_string',
            field=models.TextField(null=True),
        ),
    ]
