# Generated by Django 3.2.5 on 2021-09-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_event_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='application.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='application.customuser'),
            preserve_default=False,
        ),
    ]
