# Generated by Django 3.2.5 on 2021-09-10 10:24

import application.models.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_event__location_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('precipitation', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('wind_direction', models.IntegerField(null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('weather_date', models.DateTimeField(validators=[application.models.validators.validate_start_time])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
