# Generated by Django 3.2.5 on 2021-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
