# Generated by Django 3.2.5 on 2021-09-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_event__location_string'),
        ('application', '0007_auto_20210921_1237'),
    ]

    operations = [
    ]
