# Generated by Django 3.2.5 on 2021-09-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210925_0518'),
        ('application', '0009_event_weather'),
    ]

    operations = [
    ]
