# Generated by Django 3.2.5 on 2021-09-26 07:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_event_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('traffic_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField()),
                ('road_closed', models.BooleanField(default=False)),
                ('severity', models.IntegerField()),
                ('traffic_type', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
