# Generated by Django 3.2.5 on 2021-09-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_merge_0009_auto_20210925_0518_0009_event_weather'),
        ('application', '0010_traffic'),
    ]

    operations = [
    ]
