# Generated by Django 3.2.5 on 2021-09-30 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_merge_20210926_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('read_at', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('GEN', 'General'), ('MSG', 'Message'), ('DST', 'Distance Alert')], default='GEN', max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='application.event')),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
