# Generated by Django 3.2.5 on 2021-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='static/application/images/default.png', null=True, upload_to='uploads/profile_images'),
        ),
    ]
