# Generated by Django 3.2.5 on 2021-10-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='static/application/images/default-blue.png', upload_to='uploads/profile_images'),
        ),
    ]
