name: Django CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/checkout@v2
    - name: Install APT dependencies
      run: sudo apt-get update && sudo apt-get install gdal-bin binutils libproj-dev libgdal-dev libsqlite3-mod-spatialite
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==$(gdal-config --version)
        pip install -r src/application/requirements.txt
    - name: Run PyLint
      if: ${{ always() }}
      run: |
        cp .env.github ./src/.env.readonly
        export DJANGO_SETTINGS_MODULE=ride_with_me.settings
        pylint --load-plugins pylint_django src/application
    - name: Run Tests
      if: ${{ always() }}
      run: |
        pytest src/application/tests --cov=application/views --cov-report term-missing
